  #设置端口及二级域名
server:
  port: 80
  context-path: /base

#Spring 配置
spring:
  #设置资源路径
  resources:
    static-locations: file:${system.local.imp-path},classpath:/static/,classpath:/public/,classpath:/META-INF/resources
  mvc:
    static-path-pattern: /**
  #设置jpa  
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
  #设置编码  
  http : 
      encoding: 
        charset: UTF-8
        enabled: true
        force: true    
  #设置redis        
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    database: 0
    
#环境配置 
system: 
  local: 
    #设置德鲁伊数据连接池
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    min-idle: 10
    max-active: 50
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-return: false
    test-on-borrow: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
    use-global-data-source-stat: true
    #上传图片存储路径
    img-path: C:/file
    #设置上传文件大小
    max-file-size: 10MB
    max-request-size: 10MB

       